"""Public export contracts pinned from source HEAD 3b9fe76, before lazy edits."""

ROOT_EXPORT_MODULES = {
    "AppendOutcome": "aluclu.cognition",
    "CognitionError": "aluclu.cognition",
    "EncryptedLedger": "aluclu.cognition",
    "InputBoundaryError": "aluclu.cognition",
    "LedgerCursorCheckpoint": "aluclu.cognition",
    "LedgerRecord": "aluclu.cognition",
    "LedgerSecurityScope": "aluclu.cognition",
    "SafeStateCodec": "aluclu.cognition",
    "StateIntegrityError": "aluclu.cognition",
    "VerifiedLedgerCursor": "aluclu.cognition",
    "VerifiedLedgerSession": "aluclu.cognition",
    "canonical_json_bytes": "aluclu.cognition",
    "strict_json_loads": "aluclu.cognition",
    "validate_event_id": "aluclu.cognition",
    "compress_slot": "aluclu.compression",
    "factor_matrix": "aluclu.compression",
    "truncate_factors": "aluclu.compression",
    "truncate_factors_with_error": "aluclu.compression",
    "AlucluConfig": "aluclu.config",
    "EpisodicMemoryConfig": "aluclu.config",
    "ExactCacheConfig": "aluclu.config",
    "GatedDeltaConfig": "aluclu.config",
    "BoundedEpisodicMemory": "aluclu.episodic",
    "MassConservingRouter": "aluclu.episodic",
    "ResidualSurpriseCache": "aluclu.exact_cache",
    "GatedDeltaRule2": "aluclu.gated_delta",
    "BoundedLocalAttention": "aluclu.local_attention",
    "parameter_count": "aluclu.metrics",
    "tensor_tree_bytes": "aluclu.metrics",
    "AlucluBlock": "aluclu.model",
    "AlucluLanguageModel": "aluclu.model",
    "AlucluLanguageModelOutput": "aluclu.model",
    "MQARBatch": "aluclu.mqar",
    "generate_mqar_batch": "aluclu.mqar",
    "mqar_accuracy": "aluclu.mqar",
    "build_research_config": "aluclu.presets",
    "TensorSketch": "aluclu.sketch",
    "AlucluBlockState": "aluclu.state",
    "AlucluModelState": "aluclu.state",
    "EpisodicState": "aluclu.state",
    "ExactCacheState": "aluclu.state",
    "GatedDeltaState": "aluclu.state",
    "LocalAttentionState": "aluclu.state",
    "MemorySlot": "aluclu.state",
    "ZOOLOGY_ICLR24_COMMIT": "aluclu.zoology_mqar",
    "ZOOLOGY_ICLR24_RAW_PROTOCOL_ID": "aluclu.zoology_mqar",
    "ZOOLOGY_ICLR24_REPAIRED_PROTOCOL_ID": "aluclu.zoology_mqar",
    "ZOOLOGY_MQAR_IGNORE_INDEX": "aluclu.zoology_mqar",
    "ZoologyMQARBatch": "aluclu.zoology_mqar",
    "ZoologyMQARConfig": "aluclu.zoology_mqar",
    "generate_zoology_mqar_batch": "aluclu.zoology_mqar",
    "zoology_mqar_accuracy": "aluclu.zoology_mqar",
    "zoology_mqar_loss": "aluclu.zoology_mqar",
}
R0_EXPORT_MODULES = {
    "CanonicalEvidenceError": "aluclu.alc_r0.canonical",
    "canonical_json_bytes": "aluclu.alc_r0.canonical",
    "canonical_jsonl_bytes": "aluclu.alc_r0.canonical",
    "normalize_evidence_path": "aluclu.alc_r0.canonical",
    "parse_canonical_json": "aluclu.alc_r0.canonical",
    "parse_canonical_jsonl": "aluclu.alc_r0.canonical",
    "sha256_bytes": "aluclu.alc_r0.canonical",
    "validate_evidence_paths": "aluclu.alc_r0.canonical",
    "SMOLLM2_135M_CONFIG": "aluclu.alc_r0.host",
    "HostLoadError": "aluclu.alc_r0.host",
    "PinnedHostConfig": "aluclu.alc_r0.host",
    "VerifiedHost": "aluclu.alc_r0.host",
    "load_verified_host": "aluclu.alc_r0.host",
    "R0SchemaValidationError": "aluclu.alc_r0.schema_validation",
    "validate_r0_document": "aluclu.alc_r0.schema_validation",
}
ROOT_ALL = [
    "ZOOLOGY_ICLR24_COMMIT",
    "ZOOLOGY_ICLR24_RAW_PROTOCOL_ID",
    "ZOOLOGY_ICLR24_REPAIRED_PROTOCOL_ID",
    "ZOOLOGY_MQAR_IGNORE_INDEX",
    "AlucluBlock",
    "AlucluBlockState",
    "AlucluConfig",
    "AlucluLanguageModel",
    "AlucluLanguageModelOutput",
    "AlucluModelState",
    "AppendOutcome",
    "BoundedEpisodicMemory",
    "BoundedLocalAttention",
    "CognitionError",
    "EncryptedLedger",
    "EpisodicMemoryConfig",
    "EpisodicState",
    "ExactCacheConfig",
    "ExactCacheState",
    "GatedDeltaConfig",
    "GatedDeltaRule2",
    "GatedDeltaState",
    "InputBoundaryError",
    "LedgerCursorCheckpoint",
    "LedgerRecord",
    "LedgerSecurityScope",
    "LocalAttentionState",
    "MQARBatch",
    "MassConservingRouter",
    "MemorySlot",
    "ResidualSurpriseCache",
    "SafeStateCodec",
    "StateIntegrityError",
    "TensorSketch",
    "VerifiedLedgerCursor",
    "VerifiedLedgerSession",
    "ZoologyMQARBatch",
    "ZoologyMQARConfig",
    "__version__",
    "build_research_config",
    "canonical_json_bytes",
    "compress_slot",
    "factor_matrix",
    "generate_mqar_batch",
    "generate_zoology_mqar_batch",
    "mqar_accuracy",
    "parameter_count",
    "strict_json_loads",
    "tensor_tree_bytes",
    "truncate_factors",
    "truncate_factors_with_error",
    "validate_event_id",
    "zoology_mqar_accuracy",
    "zoology_mqar_loss",
]
R0_ALL = [
    "SMOLLM2_135M_CONFIG",
    "CanonicalEvidenceError",
    "HostLoadError",
    "PinnedHostConfig",
    "R0SchemaValidationError",
    "VerifiedHost",
    "canonical_json_bytes",
    "canonical_jsonl_bytes",
    "load_verified_host",
    "normalize_evidence_path",
    "parse_canonical_json",
    "parse_canonical_jsonl",
    "sha256_bytes",
    "validate_evidence_paths",
    "validate_r0_document",
]
