"""Cognition public exports, resolved lazily from their original modules.

Pure contracts/persistence imports do not require key or ledger dependencies.
Explicit crypto exports and star imports retain their actual dependency requirements.
"""

from importlib import import_module as _import_module

_EXPORTS = {
    "ActiveCalibrationProfileV1": (
        "aluclu.cognition.calibration",
        "ActiveCalibrationProfileV1",
    ),
    "CalibrationActivationScope": (
        "aluclu.cognition.calibration",
        "CalibrationActivationScope",
    ),
    "CalibrationArtifactV1": ("aluclu.cognition.calibration", "CalibrationArtifactV1"),
    "CalibrationCompatibilityRequirementsV1": (
        "aluclu.cognition.calibration",
        "CalibrationCompatibilityRequirementsV1",
    ),
    "CalibrationDeploymentStatus": (
        "aluclu.cognition.calibration",
        "CalibrationDeploymentStatus",
    ),
    "CalibrationDisabledReason": (
        "aluclu.cognition.calibration",
        "CalibrationDisabledReason",
    ),
    "CalibrationProfileUnavailableReason": (
        "aluclu.cognition.calibration",
        "CalibrationProfileUnavailableReason",
    ),
    "CalibrationProfileUnavailableV1": (
        "aluclu.cognition.calibration",
        "CalibrationProfileUnavailableV1",
    ),
    "CalibrationProfileV1": ("aluclu.cognition.calibration", "CalibrationProfileV1"),
    "CalibrationPurpose": ("aluclu.cognition.calibration", "CalibrationPurpose"),
    "CalibrationSpecV1": ("aluclu.cognition.calibration", "CalibrationSpecV1"),
    "CalibrationStatisticalStatus": (
        "aluclu.cognition.calibration",
        "CalibrationStatisticalStatus",
    ),
    "ExplicitCalibrationTestHarnessV1": (
        "aluclu.cognition.calibration",
        "ExplicitCalibrationTestHarnessV1",
    ),
    "LabeledRecallExampleV1": (
        "aluclu.cognition.calibration",
        "LabeledRecallExampleV1",
    ),
    "LabelIndependenceStatus": (
        "aluclu.cognition.calibration",
        "LabelIndependenceStatus",
    ),
    "LabelProvenanceManifestV1": (
        "aluclu.cognition.calibration",
        "LabelProvenanceManifestV1",
    ),
    "ThresholdCalibrationV1": (
        "aluclu.cognition.calibration",
        "ThresholdCalibrationV1",
    ),
    "ThresholdSelectionRule": (
        "aluclu.cognition.calibration",
        "ThresholdSelectionRule",
    ),
    "activate_calibration_profile": (
        "aluclu.cognition.calibration",
        "activate_calibration_profile",
    ),
    "build_calibration_artifact": (
        "aluclu.cognition.calibration",
        "build_calibration_artifact",
    ),
    "calibration_artifact_from_json_value": (
        "aluclu.cognition.calibration",
        "calibration_artifact_from_json_value",
    ),
    "calibration_artifact_to_json_value": (
        "aluclu.cognition.calibration",
        "calibration_artifact_to_json_value",
    ),
    "calibration_spec_from_json_value": (
        "aluclu.cognition.calibration",
        "calibration_spec_from_json_value",
    ),
    "calibration_spec_to_json_value": (
        "aluclu.cognition.calibration",
        "calibration_spec_to_json_value",
    ),
    "clopper_pearson_upper_bound": (
        "aluclu.cognition.calibration",
        "clopper_pearson_upper_bound",
    ),
    "decode_calibration_artifact": (
        "aluclu.cognition.calibration",
        "decode_calibration_artifact",
    ),
    "decode_calibration_spec": (
        "aluclu.cognition.calibration",
        "decode_calibration_spec",
    ),
    "decode_label_provenance_manifest": (
        "aluclu.cognition.calibration",
        "decode_label_provenance_manifest",
    ),
    "decode_labeled_recall_example": (
        "aluclu.cognition.calibration",
        "decode_labeled_recall_example",
    ),
    "derive_calibration_artifact_digest": (
        "aluclu.cognition.calibration",
        "derive_calibration_artifact_digest",
    ),
    "derive_calibration_spec_digest": (
        "aluclu.cognition.calibration",
        "derive_calibration_spec_digest",
    ),
    "derive_label_provenance_manifest_digest": (
        "aluclu.cognition.calibration",
        "derive_label_provenance_manifest_digest",
    ),
    "derive_labeled_recall_example_digest": (
        "aluclu.cognition.calibration",
        "derive_labeled_recall_example_digest",
    ),
    "encode_calibration_artifact": (
        "aluclu.cognition.calibration",
        "encode_calibration_artifact",
    ),
    "encode_calibration_spec": (
        "aluclu.cognition.calibration",
        "encode_calibration_spec",
    ),
    "encode_label_provenance_manifest": (
        "aluclu.cognition.calibration",
        "encode_label_provenance_manifest",
    ),
    "encode_labeled_recall_example": (
        "aluclu.cognition.calibration",
        "encode_labeled_recall_example",
    ),
    "explicit_calibration_test_harness": (
        "aluclu.cognition.calibration",
        "explicit_calibration_test_harness",
    ),
    "label_provenance_manifest_from_json_value": (
        "aluclu.cognition.calibration",
        "label_provenance_manifest_from_json_value",
    ),
    "label_provenance_manifest_to_json_value": (
        "aluclu.cognition.calibration",
        "label_provenance_manifest_to_json_value",
    ),
    "labeled_recall_example": (
        "aluclu.cognition.calibration",
        "labeled_recall_example",
    ),
    "labeled_recall_example_from_json_value": (
        "aluclu.cognition.calibration",
        "labeled_recall_example_from_json_value",
    ),
    "labeled_recall_example_to_json_value": (
        "aluclu.cognition.calibration",
        "labeled_recall_example_to_json_value",
    ),
    "threshold_calibration_from_json_value": (
        "aluclu.cognition.calibration",
        "threshold_calibration_from_json_value",
    ),
    "threshold_calibration_to_json_value": (
        "aluclu.cognition.calibration",
        "threshold_calibration_to_json_value",
    ),
    "SafeStateCodec": ("aluclu.cognition.codec", "SafeStateCodec"),
    "canonical_json_bytes": ("aluclu.cognition.codec", "canonical_json_bytes"),
    "strict_json_loads": ("aluclu.cognition.codec", "strict_json_loads"),
    "validate_event_id": ("aluclu.cognition.codec", "validate_event_id"),
    "AppendOutcome": ("aluclu.cognition.contracts", "AppendOutcome"),
    "CognitionError": ("aluclu.cognition.contracts", "CognitionError"),
    "InputBoundaryError": ("aluclu.cognition.contracts", "InputBoundaryError"),
    "KeyProvider": ("aluclu.cognition.contracts", "KeyProvider"),
    "KeyProviderUnavailable": ("aluclu.cognition.contracts", "KeyProviderUnavailable"),
    "LedgerCapabilityUnavailable": (
        "aluclu.cognition.contracts",
        "LedgerCapabilityUnavailable",
    ),
    "LedgerConflictError": ("aluclu.cognition.contracts", "LedgerConflictError"),
    "LedgerCursorCheckpoint": ("aluclu.cognition.contracts", "LedgerCursorCheckpoint"),
    "LedgerError": ("aluclu.cognition.contracts", "LedgerError"),
    "LedgerIntegrityError": ("aluclu.cognition.contracts", "LedgerIntegrityError"),
    "LedgerKeyError": ("aluclu.cognition.contracts", "LedgerKeyError"),
    "LedgerLifecycleError": ("aluclu.cognition.contracts", "LedgerLifecycleError"),
    "LedgerMigrationRequired": (
        "aluclu.cognition.contracts",
        "LedgerMigrationRequired",
    ),
    "LedgerRecord": ("aluclu.cognition.contracts", "LedgerRecord"),
    "LedgerRollbackError": ("aluclu.cognition.contracts", "LedgerRollbackError"),
    "LedgerSecurityScope": ("aluclu.cognition.contracts", "LedgerSecurityScope"),
    "LedgerSnapshotChanged": ("aluclu.cognition.contracts", "LedgerSnapshotChanged"),
    "LedgerVerificationStats": (
        "aluclu.cognition.contracts",
        "LedgerVerificationStats",
    ),
    "PersistenceError": ("aluclu.cognition.contracts", "PersistenceError"),
    "StateIntegrityError": ("aluclu.cognition.contracts", "StateIntegrityError"),
    "UnsafePathError": ("aluclu.cognition.contracts", "UnsafePathError"),
    "DirectoryRecordKeyStore": ("aluclu.cognition.keys", "DirectoryRecordKeyStore"),
    "FileKeyProvider": ("aluclu.cognition.keys", "FileKeyProvider"),
    "FileRecordKeyStore": ("aluclu.cognition.keys", "FileRecordKeyStore"),
    "KeyringKeyProvider": ("aluclu.cognition.keys", "KeyringKeyProvider"),
    "KeyringRecordKeyStore": ("aluclu.cognition.keys", "KeyringRecordKeyStore"),
    "RecordKeyReference": ("aluclu.cognition.keys", "RecordKeyReference"),
    "RecordKeyState": ("aluclu.cognition.keys", "RecordKeyState"),
    "RecordKeyStore": ("aluclu.cognition.keys", "RecordKeyStore"),
    "RecordKeyStoreProfile": ("aluclu.cognition.keys", "RecordKeyStoreProfile"),
    "StaticKeyProvider": ("aluclu.cognition.keys", "StaticKeyProvider"),
    "create_record_key_store": ("aluclu.cognition.keys", "create_record_key_store"),
    "EncryptedLedger": ("aluclu.cognition.ledger", "EncryptedLedger"),
    "VerifiedLedgerCursor": ("aluclu.cognition.ledger", "VerifiedLedgerCursor"),
    "VerifiedLedgerSession": ("aluclu.cognition.ledger", "VerifiedLedgerSession"),
    "BoundarySignalDigestsV1": (
        "aluclu.cognition.observation",
        "BoundarySignalDigestsV1",
    ),
    "CanonicalJsonValue": ("aluclu.cognition.observation", "CanonicalJsonValue"),
    "CanonicalObservationV1": (
        "aluclu.cognition.observation",
        "CanonicalObservationV1",
    ),
    "EpisodeBoundaryDecisionV1": (
        "aluclu.cognition.observation",
        "EpisodeBoundaryDecisionV1",
    ),
    "EpisodeBoundaryReason": ("aluclu.cognition.observation", "EpisodeBoundaryReason"),
    "ObservationRequestV1": ("aluclu.cognition.observation", "ObservationRequestV1"),
    "ProvenanceV1": ("aluclu.cognition.observation", "ProvenanceV1"),
    "SensoriumCoreStateV1": ("aluclu.cognition.observation", "SensoriumCoreStateV1"),
    "SourceKind": ("aluclu.cognition.observation", "SourceKind"),
    "build_canonical_observation": (
        "aluclu.cognition.observation",
        "build_canonical_observation",
    ),
    "canonical_observation_from_json_value": (
        "aluclu.cognition.observation",
        "canonical_observation_from_json_value",
    ),
    "canonical_observation_to_json_value": (
        "aluclu.cognition.observation",
        "canonical_observation_to_json_value",
    ),
    "decode_canonical_observation": (
        "aluclu.cognition.observation",
        "decode_canonical_observation",
    ),
    "decode_observation_request": (
        "aluclu.cognition.observation",
        "decode_observation_request",
    ),
    "decode_provenance": ("aluclu.cognition.observation", "decode_provenance"),
    "decode_sensorium_core_state": (
        "aluclu.cognition.observation",
        "decode_sensorium_core_state",
    ),
    "derive_boundary_signal_digests": (
        "aluclu.cognition.observation",
        "derive_boundary_signal_digests",
    ),
    "derive_content_digest": ("aluclu.cognition.observation", "derive_content_digest"),
    "derive_episode_id": ("aluclu.cognition.observation", "derive_episode_id"),
    "derive_request_digest": ("aluclu.cognition.observation", "derive_request_digest"),
    "derive_sensorium_core_state_digest": (
        "aluclu.cognition.observation",
        "derive_sensorium_core_state_digest",
    ),
    "encode_canonical_observation": (
        "aluclu.cognition.observation",
        "encode_canonical_observation",
    ),
    "encode_observation_request": (
        "aluclu.cognition.observation",
        "encode_observation_request",
    ),
    "encode_provenance": ("aluclu.cognition.observation", "encode_provenance"),
    "encode_sensorium_core_state": (
        "aluclu.cognition.observation",
        "encode_sensorium_core_state",
    ),
    "observation_request_from_json_value": (
        "aluclu.cognition.observation",
        "observation_request_from_json_value",
    ),
    "observation_request_to_json_value": (
        "aluclu.cognition.observation",
        "observation_request_to_json_value",
    ),
    "sensorium_core_state_from_json_value": (
        "aluclu.cognition.observation",
        "sensorium_core_state_from_json_value",
    ),
    "sensorium_core_state_to_json_value": (
        "aluclu.cognition.observation",
        "sensorium_core_state_to_json_value",
    ),
    "atomic_write_bytes": ("aluclu.cognition.persistence", "atomic_write_bytes"),
    "exclusive_file_lock": ("aluclu.cognition.persistence", "exclusive_file_lock"),
    "resolve_ledger_path": ("aluclu.cognition.persistence", "resolve_ledger_path"),
    "FeatureSimilarityV1": ("aluclu.cognition.recall_features", "FeatureSimilarityV1"),
    "RetrievalFeatureVectorV1": (
        "aluclu.cognition.recall_features",
        "RetrievalFeatureVectorV1",
    ),
    "active_feature_spec_id": (
        "aluclu.cognition.recall_features",
        "active_feature_spec_id",
    ),
    "active_normalizer_id": (
        "aluclu.cognition.recall_features",
        "active_normalizer_id",
    ),
    "active_scorer_id": ("aluclu.cognition.recall_features", "active_scorer_id"),
    "compare_feature_similarity_exact": (
        "aluclu.cognition.recall_features",
        "compare_feature_similarity_exact",
    ),
    "encode_retrieval_text": (
        "aluclu.cognition.recall_features",
        "encode_retrieval_text",
    ),
    "feature_vector_digest": (
        "aluclu.cognition.recall_features",
        "feature_vector_digest",
    ),
    "measure_feature_similarity": (
        "aluclu.cognition.recall_features",
        "measure_feature_similarity",
    ),
    "search_view_utf8": ("aluclu.cognition.recall_features", "search_view_utf8"),
    "AbstainedRecollection": ("aluclu.cognition.recollection", "AbstainedRecollection"),
    "AbstainReason": ("aluclu.cognition.recollection", "AbstainReason"),
    "AmbiguousExactRecollection": (
        "aluclu.cognition.recollection",
        "AmbiguousExactRecollection",
    ),
    "ApproximateCandidates": ("aluclu.cognition.recollection", "ApproximateCandidates"),
    "ApproximateCandidateV1": (
        "aluclu.cognition.recollection",
        "ApproximateCandidateV1",
    ),
    "CalibratedTextMatchEvidenceV1": (
        "aluclu.cognition.recollection",
        "CalibratedTextMatchEvidenceV1",
    ),
    "ConflictedRecollection": (
        "aluclu.cognition.recollection",
        "ConflictedRecollection",
    ),
    "ContentDigestRecallQuery": (
        "aluclu.cognition.recollection",
        "ContentDigestRecallQuery",
    ),
    "EventIdRecallQuery": ("aluclu.cognition.recollection", "EventIdRecallQuery"),
    "ExactOccurrenceSummaryV1": (
        "aluclu.cognition.recollection",
        "ExactOccurrenceSummaryV1",
    ),
    "ExactRecollection": ("aluclu.cognition.recollection", "ExactRecollection"),
    "IncompleteRecollection": (
        "aluclu.cognition.recollection",
        "IncompleteRecollection",
    ),
    "NoRecollection": ("aluclu.cognition.recollection", "NoRecollection"),
    "NoScanRecollection": ("aluclu.cognition.recollection", "NoScanRecollection"),
    "NoTextRecollection": ("aluclu.cognition.recollection", "NoTextRecollection"),
    "RecallBasis": ("aluclu.cognition.recollection", "RecallBasis"),
    "RecallContinuationV1": ("aluclu.cognition.recollection", "RecallContinuationV1"),
    "RecallExecutionPolicyV1": (
        "aluclu.cognition.recollection",
        "RecallExecutionPolicyV1",
    ),
    "RecallFiltersV1": ("aluclu.cognition.recollection", "RecallFiltersV1"),
    "RecallPolicyTighteningV1": (
        "aluclu.cognition.recollection",
        "RecallPolicyTighteningV1",
    ),
    "RecollectionWorkV1": ("aluclu.cognition.recollection", "RecollectionWorkV1"),
    "TextRecallQuery": ("aluclu.cognition.recollection", "TextRecallQuery"),
    "recall": ("aluclu.cognition.recollection", "recall"),
    "tighten_recall_policy": ("aluclu.cognition.recollection", "tighten_recall_policy"),
    "RECONSOLIDATION_SCHEMA": (
        "aluclu.cognition.reconsolidation",
        "RECONSOLIDATION_SCHEMA",
    ),
    "ReconsolidationProposalV1": (
        "aluclu.cognition.reconsolidation",
        "ReconsolidationProposalV1",
    ),
    "ReconsolidationReason": (
        "aluclu.cognition.reconsolidation",
        "ReconsolidationReason",
    ),
    "ReconsolidationRecordV1": (
        "aluclu.cognition.reconsolidation",
        "ReconsolidationRecordV1",
    ),
    "commit_reconsolidation": (
        "aluclu.cognition.reconsolidation",
        "commit_reconsolidation",
    ),
    "propose_reconsolidation": (
        "aluclu.cognition.reconsolidation",
        "propose_reconsolidation",
    ),
    "reconsolidation_record_from_json_value": (
        "aluclu.cognition.reconsolidation",
        "reconsolidation_record_from_json_value",
    ),
    "reconsolidation_record_to_json_value": (
        "aluclu.cognition.reconsolidation",
        "reconsolidation_record_to_json_value",
    ),
    "SENSORIUM_REPLAY_CONTINUATION_MAX_BYTES": (
        "aluclu.cognition.sensorium",
        "SENSORIUM_REPLAY_CONTINUATION_MAX_BYTES",
    ),
    "SENSORIUM_REPLAY_MAX_RECORDS": (
        "aluclu.cognition.sensorium",
        "SENSORIUM_REPLAY_MAX_RECORDS",
    ),
    "BoundaryProfileV1": ("aluclu.cognition.sensorium", "BoundaryProfileV1"),
    "CanonicalizedObservationV1": (
        "aluclu.cognition.sensorium",
        "CanonicalizedObservationV1",
    ),
    "IngestRejectionCode": ("aluclu.cognition.sensorium", "IngestRejectionCode"),
    "IngestStatus": ("aluclu.cognition.sensorium", "IngestStatus"),
    "ObservationAcceptedV1": ("aluclu.cognition.sensorium", "ObservationAcceptedV1"),
    "ObservationReceiptV1": ("aluclu.cognition.sensorium", "ObservationReceiptV1"),
    "ObservationRejectedV1": ("aluclu.cognition.sensorium", "ObservationRejectedV1"),
    "ReceiptClass": ("aluclu.cognition.sensorium", "ReceiptClass"),
    "SensoriumBootstrapReplayRequiredV1": (
        "aluclu.cognition.sensorium",
        "SensoriumBootstrapReplayRequiredV1",
    ),
    "SensoriumReplayCompleteV1": (
        "aluclu.cognition.sensorium",
        "SensoriumReplayCompleteV1",
    ),
    "SensoriumReplayContinuationV1": (
        "aluclu.cognition.sensorium",
        "SensoriumReplayContinuationV1",
    ),
    "SensoriumReplayIncompleteV1": (
        "aluclu.cognition.sensorium",
        "SensoriumReplayIncompleteV1",
    ),
    "SensoriumReplayPagePolicyV1": (
        "aluclu.cognition.sensorium",
        "SensoriumReplayPagePolicyV1",
    ),
    "SensoriumReplayPageWorkV1": (
        "aluclu.cognition.sensorium",
        "SensoriumReplayPageWorkV1",
    ),
    "SensoriumStateV1": ("aluclu.cognition.sensorium", "SensoriumStateV1"),
    "baseline_boundary_profile": (
        "aluclu.cognition.sensorium",
        "baseline_boundary_profile",
    ),
    "bootstrap_replay_to_json_value": (
        "aluclu.cognition.sensorium",
        "bootstrap_replay_to_json_value",
    ),
    "boundary_profile_to_json_value": (
        "aluclu.cognition.sensorium",
        "boundary_profile_to_json_value",
    ),
    "canonicalize_observation": (
        "aluclu.cognition.sensorium",
        "canonicalize_observation",
    ),
    "classify_observation_receipt": (
        "aluclu.cognition.sensorium",
        "classify_observation_receipt",
    ),
    "decode_sensorium_state": ("aluclu.cognition.sensorium", "decode_sensorium_state"),
    "encode_sensorium_state": ("aluclu.cognition.sensorium", "encode_sensorium_state"),
    "ingest_observation": ("aluclu.cognition.sensorium", "ingest_observation"),
    "initialize_empty_sensorium_state": (
        "aluclu.cognition.sensorium",
        "initialize_empty_sensorium_state",
    ),
    "observation_accepted_to_json_value": (
        "aluclu.cognition.sensorium",
        "observation_accepted_to_json_value",
    ),
    "observation_receipt_to_json_value": (
        "aluclu.cognition.sensorium",
        "observation_receipt_to_json_value",
    ),
    "observation_rejected_to_json_value": (
        "aluclu.cognition.sensorium",
        "observation_rejected_to_json_value",
    ),
    "replay_complete_from_json_value": (
        "aluclu.cognition.sensorium",
        "replay_complete_from_json_value",
    ),
    "replay_complete_to_json_value": (
        "aluclu.cognition.sensorium",
        "replay_complete_to_json_value",
    ),
    "replay_continuation_from_json_value": (
        "aluclu.cognition.sensorium",
        "replay_continuation_from_json_value",
    ),
    "replay_continuation_to_json_value": (
        "aluclu.cognition.sensorium",
        "replay_continuation_to_json_value",
    ),
    "replay_incomplete_from_json_value": (
        "aluclu.cognition.sensorium",
        "replay_incomplete_from_json_value",
    ),
    "replay_incomplete_to_json_value": (
        "aluclu.cognition.sensorium",
        "replay_incomplete_to_json_value",
    ),
    "replay_page_policy_from_json_value": (
        "aluclu.cognition.sensorium",
        "replay_page_policy_from_json_value",
    ),
    "replay_page_policy_to_json_value": (
        "aluclu.cognition.sensorium",
        "replay_page_policy_to_json_value",
    ),
    "replay_page_work_from_json_value": (
        "aluclu.cognition.sensorium",
        "replay_page_work_from_json_value",
    ),
    "replay_page_work_to_json_value": (
        "aluclu.cognition.sensorium",
        "replay_page_work_to_json_value",
    ),
    "replay_sensorium_page": ("aluclu.cognition.sensorium", "replay_sensorium_page"),
    "sensorium_state_from_json_value": (
        "aluclu.cognition.sensorium",
        "sensorium_state_from_json_value",
    ),
    "sensorium_state_to_json_value": (
        "aluclu.cognition.sensorium",
        "sensorium_state_to_json_value",
    ),
}

__all__ = [
    "RECONSOLIDATION_SCHEMA",
    "SENSORIUM_REPLAY_CONTINUATION_MAX_BYTES",
    "SENSORIUM_REPLAY_MAX_RECORDS",
    "AbstainReason",
    "AbstainedRecollection",
    "ActiveCalibrationProfileV1",
    "AmbiguousExactRecollection",
    "AppendOutcome",
    "ApproximateCandidateV1",
    "ApproximateCandidates",
    "BoundaryProfileV1",
    "BoundarySignalDigestsV1",
    "CalibratedTextMatchEvidenceV1",
    "CalibrationActivationScope",
    "CalibrationArtifactV1",
    "CalibrationCompatibilityRequirementsV1",
    "CalibrationDeploymentStatus",
    "CalibrationDisabledReason",
    "CalibrationProfileUnavailableReason",
    "CalibrationProfileUnavailableV1",
    "CalibrationProfileV1",
    "CalibrationPurpose",
    "CalibrationSpecV1",
    "CalibrationStatisticalStatus",
    "CanonicalJsonValue",
    "CanonicalObservationV1",
    "CanonicalizedObservationV1",
    "CognitionError",
    "ConflictedRecollection",
    "ContentDigestRecallQuery",
    "DirectoryRecordKeyStore",
    "EncryptedLedger",
    "EpisodeBoundaryDecisionV1",
    "EpisodeBoundaryReason",
    "EventIdRecallQuery",
    "ExactOccurrenceSummaryV1",
    "ExactRecollection",
    "ExplicitCalibrationTestHarnessV1",
    "FeatureSimilarityV1",
    "FileKeyProvider",
    "FileRecordKeyStore",
    "IncompleteRecollection",
    "IngestRejectionCode",
    "IngestStatus",
    "InputBoundaryError",
    "KeyProvider",
    "KeyProviderUnavailable",
    "KeyringKeyProvider",
    "KeyringRecordKeyStore",
    "LabelIndependenceStatus",
    "LabelProvenanceManifestV1",
    "LabeledRecallExampleV1",
    "LedgerCapabilityUnavailable",
    "LedgerConflictError",
    "LedgerCursorCheckpoint",
    "LedgerError",
    "LedgerIntegrityError",
    "LedgerKeyError",
    "LedgerLifecycleError",
    "LedgerMigrationRequired",
    "LedgerRecord",
    "LedgerRollbackError",
    "LedgerSecurityScope",
    "LedgerSnapshotChanged",
    "LedgerVerificationStats",
    "NoRecollection",
    "NoScanRecollection",
    "NoTextRecollection",
    "ObservationAcceptedV1",
    "ObservationReceiptV1",
    "ObservationRejectedV1",
    "ObservationRequestV1",
    "PersistenceError",
    "ProvenanceV1",
    "RecallBasis",
    "RecallContinuationV1",
    "RecallExecutionPolicyV1",
    "RecallFiltersV1",
    "RecallPolicyTighteningV1",
    "ReceiptClass",
    "RecollectionWorkV1",
    "ReconsolidationProposalV1",
    "ReconsolidationReason",
    "ReconsolidationRecordV1",
    "RecordKeyReference",
    "RecordKeyState",
    "RecordKeyStore",
    "RecordKeyStoreProfile",
    "RetrievalFeatureVectorV1",
    "SafeStateCodec",
    "SensoriumBootstrapReplayRequiredV1",
    "SensoriumCoreStateV1",
    "SensoriumReplayCompleteV1",
    "SensoriumReplayContinuationV1",
    "SensoriumReplayIncompleteV1",
    "SensoriumReplayPagePolicyV1",
    "SensoriumReplayPageWorkV1",
    "SensoriumStateV1",
    "SourceKind",
    "StateIntegrityError",
    "StaticKeyProvider",
    "TextRecallQuery",
    "ThresholdCalibrationV1",
    "ThresholdSelectionRule",
    "UnsafePathError",
    "VerifiedLedgerCursor",
    "VerifiedLedgerSession",
    "activate_calibration_profile",
    "active_feature_spec_id",
    "active_normalizer_id",
    "active_scorer_id",
    "atomic_write_bytes",
    "baseline_boundary_profile",
    "bootstrap_replay_to_json_value",
    "boundary_profile_to_json_value",
    "build_calibration_artifact",
    "build_canonical_observation",
    "calibration_artifact_from_json_value",
    "calibration_artifact_to_json_value",
    "calibration_spec_from_json_value",
    "calibration_spec_to_json_value",
    "canonical_json_bytes",
    "canonical_observation_from_json_value",
    "canonical_observation_to_json_value",
    "canonicalize_observation",
    "classify_observation_receipt",
    "clopper_pearson_upper_bound",
    "commit_reconsolidation",
    "compare_feature_similarity_exact",
    "create_record_key_store",
    "decode_calibration_artifact",
    "decode_calibration_spec",
    "decode_canonical_observation",
    "decode_label_provenance_manifest",
    "decode_labeled_recall_example",
    "decode_observation_request",
    "decode_provenance",
    "decode_sensorium_core_state",
    "decode_sensorium_state",
    "derive_boundary_signal_digests",
    "derive_calibration_artifact_digest",
    "derive_calibration_spec_digest",
    "derive_content_digest",
    "derive_episode_id",
    "derive_label_provenance_manifest_digest",
    "derive_labeled_recall_example_digest",
    "derive_request_digest",
    "derive_sensorium_core_state_digest",
    "encode_calibration_artifact",
    "encode_calibration_spec",
    "encode_canonical_observation",
    "encode_label_provenance_manifest",
    "encode_labeled_recall_example",
    "encode_observation_request",
    "encode_provenance",
    "encode_retrieval_text",
    "encode_sensorium_core_state",
    "encode_sensorium_state",
    "exclusive_file_lock",
    "explicit_calibration_test_harness",
    "feature_vector_digest",
    "ingest_observation",
    "initialize_empty_sensorium_state",
    "label_provenance_manifest_from_json_value",
    "label_provenance_manifest_to_json_value",
    "labeled_recall_example",
    "labeled_recall_example_from_json_value",
    "labeled_recall_example_to_json_value",
    "measure_feature_similarity",
    "observation_accepted_to_json_value",
    "observation_receipt_to_json_value",
    "observation_rejected_to_json_value",
    "observation_request_from_json_value",
    "observation_request_to_json_value",
    "propose_reconsolidation",
    "recall",
    "reconsolidation_record_from_json_value",
    "reconsolidation_record_to_json_value",
    "replay_complete_from_json_value",
    "replay_complete_to_json_value",
    "replay_continuation_from_json_value",
    "replay_continuation_to_json_value",
    "replay_incomplete_from_json_value",
    "replay_incomplete_to_json_value",
    "replay_page_policy_from_json_value",
    "replay_page_policy_to_json_value",
    "replay_page_work_from_json_value",
    "replay_page_work_to_json_value",
    "replay_sensorium_page",
    "resolve_ledger_path",
    "search_view_utf8",
    "sensorium_core_state_from_json_value",
    "sensorium_core_state_to_json_value",
    "sensorium_state_from_json_value",
    "sensorium_state_to_json_value",
    "strict_json_loads",
    "threshold_calibration_from_json_value",
    "threshold_calibration_to_json_value",
    "tighten_recall_policy",
    "validate_event_id",
]


def __getattr__(name: str):
    try:
        module_name, symbol_name = _EXPORTS[name]
    except KeyError:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from None
    value = getattr(_import_module(module_name), symbol_name)
    globals()[name] = value
    return value


def __dir__():
    return sorted(set(globals()) | set(__all__))
